travis:
  secure:
    BINSTAR_TOKEN: dhv4E5tCPx4XsW60cniqRv5ZHtVOMxZk3DVJKM5L2cYUEoO0t8x8Lbp5BwqTuHVj05dSz0MvO+hU2o1Q8vj7APmgdoX4bv6ONqpd1nzQ1Efq2fk527EayT42AbXYItU/bN/84fGiRgmE14vgN/vvErg7GmvpG6Z6r2N7ISpccd7E4n9Mjap4PQyH+BFLKRTAumHS6/lbNG2YotWvtV7+YZf3TRnvhexJEVPrFFIxG8dLC7MeF2A4WqfCl7E1CkyDs3lam4PgFr5e6AH9H/91zxmca4J6HE6PQ3r+y+i+DCOC5F6A8aYzyJD0KGl5boxeEcrsjHa+ZBHcEY91FvqP2ThBeLwP79Zk4/6nsu0hfb5RXCvPPk4TNPUbKKIdoI6nHfT//5/qdz4uCLTIrQdlxEtrbQWa4ZsNGJ/G7Q2N0FHYLnyIbkBhY0YGDCRSgKn60bJdG06fvjbVS9RchP7QlYwPtdawXbApDZF1Suht2WZYsN3v0m9zy+ixgRvfs2g2K+bHboROyhx/IYmtWtOGSvzvb6U8ONPHdVt/GJSgH6r49tRqWSr8hamBANIHQ8U1kbK/PhZw9DPn+89lCHmV1hJVBSbhLuoPz3apiQVCzMG2ww3Egr7W23ntA6nOZN/QjhzTPjjH8STa9rMQ/cxDdSENgdaTz/ZFWaoMZCNjb4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
